# Generated by Django 6.0.1 on 2026-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_tipoegreso_egreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='validado',
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
