# Generated by Django 6.0.1 on 2026-01-27 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_pago_created_at_remove_pago_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Asunto')),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta Administrativa')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTESTADA', 'Contestada'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
