# Generated by Django 6.0.1 on 2026-01-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calle',
            name='fraccionamiento',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='numero_interior',
        ),
        migrations.RemoveField(
            model_name='fraccionamiento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fraccionamiento',
            name='logo',
        ),
        migrations.AddField(
            model_name='casa',
            name='fraccionamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='inmuebles.fraccionamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='calle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casas', to='inmuebles.calle'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero_exterior',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fraccionamiento',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
