# Generated by Django 6.0.1 on 2026-01-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_remove_calle_fraccionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraccionamiento',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='fraccionamiento/'),
        ),
        migrations.AddField(
            model_name='fraccionamiento',
            name='titulo_header',
            field=models.CharField(default='Bienvenidos a nuestra Comunidad', max_length=150),
        ),
        migrations.AlterField(
            model_name='casa',
            name='calle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.calle'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='fraccionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.fraccionamiento'),
        ),
        migrations.AlterField(
            model_name='fraccionamiento',
            name='direccion',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
