# Generated by Django 6.0.1 on 2026-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_fraccionamiento_imagen_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraccionamiento',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
