# Generated by Django 6.0.1 on 2026-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_fraccionamiento_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraccionamiento',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
