# Generated by Django 6.0.1 on 2026-01-16 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('ALBANIL', 'Albañilería'), ('JARDINERIA', 'Jardinería'), ('CERRAJERIA', 'Cerrajería'), ('GAS', 'Gas'), ('INTERNET', 'Internet/TV'), ('LIMPIEZA', 'Limpieza'), ('VETERINARIA', 'Mascotas'), ('OTRO', 'Otros')], default='OTRO', max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total_puntos', models.IntegerField(default=0)),
                ('total_votos', models.IntegerField(default=0)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('servicio', 'usuario')},
            },
        ),
    ]
