# Generated by Django 6.0.1 on 2026-01-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_remove_calle_fraccionamiento_and_more'),
        ('usuarios', '0002_remove_usuario_foto_usuario_avatar_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='inmuebles.casa')),
            ],
        ),
    ]
