# Generated by Django 6.0.1 on 2026-01-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_fraccionamiento_direccion'),
        ('seguridad', '0006_remove_accesotrabajador_dentro_and_more'),
        ('usuarios', '0003_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fraccionamiento_administrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='inmuebles.fraccionamiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
