# Generated by Django 6.0.1 on 2026-01-07 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('placas', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_llegada', models.DateTimeField()),
                ('token', models.CharField(blank=True, max_length=20, unique=True)),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='codigos_qr/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'En el Fraccionamiento'), ('FINALIZADA', 'Salió')], default='PENDIENTE', max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmuebles.casa')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
