# Generated by Django 6.0.1 on 2026-01-13 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='token',
        ),
        migrations.AddField(
            model_name='visita',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INGRESO', 'Ingresó'), ('SALIO', 'Salió')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
