# Generated by Django 6.0.1 on 2026-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_remove_visita_casa_remove_visita_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='bitacora_media/'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
