# Generated by Django 6.0.1 on 2026-01-13 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_bitacora_media_alter_bitacora_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('dentro', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='visita',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_salida_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo',
            field=models.CharField(choices=[('VISITA', 'Visita Normal'), ('PROVEEDOR', 'Proveedor / Servicio')], default='VISITA', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INGRESO', 'Dentro del Fracc'), ('SALIO', 'Finalizado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
