# Generated by Django 6.0.1 on 2026-01-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_accesotrabajador_visita_empresa_and_more'),
        ('usuarios', '0003_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.trabajador'),
        ),
    ]
