# Generated by Django 6.0.1 on 2026-01-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0004_alter_fraccionamiento_direccion'),
        ('seguridad', '0005_accesotrabajador_trabajador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesotrabajador',
            name='dentro',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='guardia',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='media',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='imagen_qr',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='residente',
        ),
        migrations.AddField(
            model_name='accesotrabajador',
            name='guardia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fraccionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.fraccionamiento'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visita',
            name='casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='inmuebles.casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='estatus',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='valido_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_llegada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nombre_visitante',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo',
            field=models.CharField(choices=[('VISITA', 'Visita Casual'), ('PROVEEDOR', 'Proveedor / Servicio'), ('PAQUETERIA', 'Paquetería'), ('UBER', 'Uber / Taxi')], default='VISITA', max_length=20),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='trabajadores/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('casa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='inmuebles.casa')),
            ],
        ),
        migrations.AlterField(
            model_name='accesotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.trabajador'),
        ),
    ]
