# Generated by Django 6.0.1 on 2026-01-17 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_fraccionamiento_cuota_mensual'),
        ('seguridad', '0006_remove_accesotrabajador_dentro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='placas',
            new_name='placas_vehiculo',
        ),
        migrations.RemoveField(
            model_name='accesotrabajador',
            name='guardia',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='fraccionamiento',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='casa_asignada',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='codigo_qr',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='valido_hasta',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(default='Sin novedad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bitacora_img/'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='involucrados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='placas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tipo',
            field=models.CharField(choices=[('RUTINA', 'Rondín / Novedad de Rutina'), ('SOSPECHOSO', 'Actitud o Vehículo Sospechoso'), ('RUIDO', 'Ruido Excesivo / Fiesta'), ('ACCESO', 'Intento de Acceso No Autorizado'), ('DAÑO', 'Daño a Instalaciones'), ('SERVICIO', 'Falla de Servicios (Luz/Portón)'), ('OTRO', 'Otro')], default='RUTINA', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='titulo',
            field=models.CharField(default='Registro', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacora',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='bitacora_vid/'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='inmuebles.casa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_llegada_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_programadas', to='inmuebles.casa'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nombre_visitante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo',
            field=models.CharField(choices=[('VISITA', 'Visita Familiar/Amigo'), ('PROVEEDOR', 'Proveedor/Servicio')], default='VISITA', max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
