# Generated by Django 6.0.1 on 2026-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_visita_created_at_mensajechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='tipo',
            field=models.CharField(choices=[('RUTINA', 'Rondín'), ('SOSPECHOSO', 'Sospechoso'), ('RUIDO', 'Ruido'), ('ACCESO', 'Acceso Denegado'), ('DAÑO', 'Daño'), ('SERVICIO', 'Falla'), ('OTRO', 'Otro')], default='RUTINA', max_length=20),
        ),
    ]
