# Generated by Django 6.0.1 on 2026-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_alter_bitacora_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='es_para_guardia',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='es_guardia',
            field=models.BooleanField(default=False),
        ),
    ]
