# Generated by Django 6.0.1 on 2026-01-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_remove_mensajechat_es_para_guardia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajechat',
            options={'ordering': ['fecha']},
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tipo',
            field=models.CharField(choices=[('VISITA', 'Visita Familiar/Amigo'), ('PROVEEDOR', 'Proveedor/Servicio'), ('TAXI', 'Taxi/Uber/Didi'), ('PAQUETERIA', 'Paquetería'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro')], default='VISITA', max_length=20),
        ),
    ]
