# Generated by Django 6.0.1 on 2026-01-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='foro_vid/'),
        ),
        migrations.AddField(
            model_name='queja',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='quejas_img/'),
        ),
        migrations.AddField(
            model_name='queja',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='quejas_vid/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro_img/'),
        ),
    ]
