# Generated by Django 6.0.1 on 2026-01-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='creador',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opcionencuesta',
            name='texto',
            field=models.CharField(max_length=100),
        ),
    ]
