# Generated by Django 6.0.1 on 2026-01-14 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_remove_encuesta_creador_alter_encuesta_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('JARDINERIA', 'Jardinería'), ('ALBANIL', 'Albañilería'), ('CERRAJERIA', 'Cerrajería'), ('GAS', 'Gas Estacionario/Cilindro'), ('AGUA', 'Pipas de Agua'), ('INTERNET', 'Técnico Internet/Cable'), ('LIMPIEZA', 'Limpieza / Doméstica'), ('VETERINARIA', 'Veterinaria / Mascotas'), ('OTRO', 'Otros Servicios')], max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_sugeridos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='comunidad.servicioexterno')),
            ],
            options={
                'unique_together': {('servicio', 'usuario')},
            },
        ),
    ]
