# Generated by Django 6.0.1 on 2026-01-28 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_servicioexterno_calificacionservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='activo',
            new_name='vigente',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='encuesta',
            old_name='fecha_creacion',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='queja',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='calificacionservicio',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='votousuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='video',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='respuesta_admin',
        ),
        migrations.RemoveField(
            model_name='queja',
            name='video',
        ),
        migrations.RemoveField(
            model_name='servicioexterno',
            name='foto',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='quejas/'),
        ),
        migrations.AddField(
            model_name='queja',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicioexterno',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votousuario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacionservicio',
            name='comentario',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacionservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.servicioexterno'),
        ),
        migrations.AlterField(
            model_name='opcionencuesta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foro/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo',
            field=models.CharField(choices=[('SOCIAL', 'Social'), ('VENTA', 'Venta'), ('SERVICIO', 'Servicio'), ('AVISO', 'Aviso Oficial')], default='SOCIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicioexterno',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicioexterno',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicioexterno',
            name='descripcion',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioexterno',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='calificacionservicio',
            name='fecha',
        ),
    ]
