# Generated by Django 6.0.1 on 2026-01-28 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_configuracioncomunidad_alter_aviso_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_grafico',
            field=models.CharField(choices=[('BARRA', 'Gráfico de Barras'), ('PASTEL', 'Gráfico de Pastel')], default='BARRA', max_length=20),
        ),
    ]
